import images from '../assets/images';
import strings from '../i18n/strings';
import {StackNav} from '../navigation/NavigationKeys';

const OnBoardingSlide = [
  {
    text: 'NA',
    img: images.onBording1,
  },
  
];

const GenderData = [
  {label: 'Male', value: 'male'},
  {label: 'Female', value: 'female'},
  {label: 'Other', value: 'other'},
];

const ProfileSetting = [
  {
    id: 1,
    title: strings.editProfile,
    icon: 'person-outline',
    route: StackNav.SetUpProfile,
    header: strings.editProfile,
  },
  {
    id: 2,
    title: strings.address,
    icon: 'location-outline',
    route: StackNav.Address,
  },
  {
    id: 2,
    title: strings.notification,
    icon: 'notifications-outline',
    route: StackNav.NotificationSetting,
  },
  {
    id: 3,
    title: strings.payment,
    icon: 'wallet-outline',
    route: StackNav.Payment,
  },
  {
    id: 4,
    title: strings.security,
    icon: 'shield-checkmark-outline',
    route: StackNav.Security,
  },
  {
    id: 5,
    title: strings.language,
    icon: 'options-outline',
    value: 'English(US)',
    route: StackNav.Language,
  },
  {
    id: 6,
    title: strings.darkMode,
    icon: 'contrast-outline',
    rightIcon: 'rightIcon',
  },
  {
    id: 7,
    title: strings.privacyPolicy,
    icon: 'lock-closed-outline',
    route: StackNav.PrivacyPolicy,
  },
  {
    id: 8,
    title: strings.helpCenter,
    icon: 'information-circle-outline',
    route: StackNav.HelpCenter,
  },
  {
    id: 8,
    title: strings.inviteFriends,
    icon: 'people-outline',
    route: StackNav.InviteFriends,
  },
];

const contactUsData = [
  {
    id: 1,
    title: 'Customer Service',
    icon: 'headset',
  },
  {
    id: 2,
    title: 'WhatsApp',
    icon: 'whatsapp',
  },
  {
    id: 3,
    title: 'Website',
    icon: 'google-earth',
  },
  {
    id: 4,
    title: 'Facebook',
    icon: 'facebook',
  },
  {
    id: 5,
    title: 'Instagram',
    icon: 'instagram',
  },
  {
    id: 6,
    title: 'Twitter',
    icon: 'twitter',
  },
];

const helperCategoryData = [
  'General',
  'Account',
  'Payment',
  'Subscription',
  'Others',
];

const helperData = [
  {
    title: 'What is Furnia?',
    description:
      'Anistream is a streaming service that offers a wide variety of anime titles.',
  },
  {
    title: 'How to use Furnia?',
    description:
      'You can sign up for Anistream by downloading the app from the App Store or Google Play Store.',
  },
  {
    title: 'How do I cancel a orders product?',
    description:
      'You can remove anime on your wishlist by clicking the heart icon on the anime details page.',
  },
  {
    title: 'Is Furnia free to use?',
    description:
      'You can subscribe to premium by clicking the premium button on the home page.',
  },
  {
    title: 'How to add promo on Furnia?',
    description:
      'You can download anime by clicking the download icon on the anime details page.',
  },
  {
    title: 'How to unsubscribe from premium?',
    description:
      'You can unsubscribe from premium by clicking the premium button on the home page.',
  },
];

const languageData = [
  {
    title: 'Suggested',
    data: [{lnName: 'English(US)'}, {lnName: 'English(UK)'}],
  },
  {
    title: 'Language',
    data: [
      {
        lnName: 'English',
      },
      {
        lnName: 'Spanish',
      },
      {
        lnName: 'French',
      },
      {
        lnName: 'German',
      },
      {
        lnName: 'Italian',
      },
      {
        lnName: 'Portuguese',
      },
      {
        lnName: 'Russian',
      },
      {
        lnName: 'Turkish',
      },
      {
        lnName: 'Chinese',
      },
      {
        lnName: 'Japanese',
      },
      {
        lnName: 'Korean',
      },
      {
        lnName: 'Arabic',
      },
      {
        lnName: 'Hindi',
      },
      {
        lnName: 'Indonesian',
      },
      {
        lnName: 'Malay',
      },
      {
        lnName: 'Thai',
      },
    ],
  },
];

const privacyPolicyData = [
  {
    title: strings.privacyPolicy1,
    description: strings.privacyPolicyDesc,
  },
  {
    title: strings.privacyPolicy2,
    description: strings.privacyPolicyDesc,
  },
  {
    title: strings.privacyPolicy3,
    description: strings.privacyPolicyDesc,
  },
  {
    title: strings.privacyPolicy2,
    description: strings.privacyPolicyDesc,
  },
  {
    title: strings.privacyPolicy3,
    description: strings.privacyPolicyDesc,
  },
  {
    title: strings.privacyPolicy2,
    description: strings.privacyPolicyDesc,
  },
  {
    title: strings.privacyPolicy3,
    description: strings.privacyPolicyDesc,
  },
];

const userDetail = [
  {
    name: 'Dracel Steward',
    description: 'arianacooper | 24.5M followers',
    imgUrl:
      'https://images.unsplash.com/photo-1527980965255-d3b416303d12?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1160&q=80',
  },
  {
    name: 'John Doe',
    description: 'johndoe | 10M followers',
    imgUrl:
      'https://images.unsplash.com/photo-1605993439219-9d09d2020fa5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mzh8fHVzZXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60',
  },
  {
    name: 'Jane Smith',
    description: 'janesmith | 5M followers',
    imgUrl:
      'https://images.unsplash.com/photo-1603415526960-f7e0328c63b1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzN8fHVzZXIlMjBwcm9maWxlJTIwd2l0aCUyMGJhY2tncm91bmR8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60',
  },
  {
    name: 'Bob Johnson',
    description: 'bobjohnson | 2M followers',
    imgUrl:
      'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8dXNlcnxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60',
  },
  {
    name: 'Sara Wilson',
    description: 'sarawilson | 1M followers',
    imgUrl:
      'https://images.unsplash.com/photo-1619895862022-09114b41f16f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjJ8fHVzZXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60',
  },
  {
    name: 'Tom Wilson',
    description: 'tomwilson | 500K followers',
    imgUrl:
      'https://images.unsplash.com/photo-1506277886164-e25aa3f4ef7f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mjl8fHVzZXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60',
  },
  {
    name: 'Alice Brown',
    description: 'alicebrown | 250K followers',
    imgUrl:
      'https://images.unsplash.com/photo-1463453091185-61582044d556?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzZ8fHVzZXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60',
  },
  {
    name: 'Emily Davis',
    description: 'emilydavis | 100K followers',
    imgUrl:
      'https://images.unsplash.com/photo-1573496799652-408c2ac9fe98?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NDV8fHVzZXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60',
  },
  {
    name: 'Mark Lee',
    description: 'marklee | 50K followers',
    imgUrl:
      'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NTN8fHVzZXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60',
  },
  {
    name: 'Laura Lee',
    description: 'lauralee | 10K followers',
    imgUrl:
      'https://images.unsplash.com/photo-1610737241336-371badac3b66?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NTJ8fHVzZXJ8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60',
  },
];

const chatData = [
  {
    id: 1,
    message: 'Hi Theresa, good morning 😄',
    time: '12:00',
    type: 'sender',
  },
  {
    id: 2,
    message: 'Hi there, good morning! How are you?',
    time: '12:01',
    type: 'receiver',
  },
  {
    id: 3,
    message: 'I am doing well, thanks for asking 😊',
    time: '12:02',
    type: 'sender',
  },
  {
    id: 4,
    message: "That's great to hear! What are your plans for the day?",
    time: '12:03',
    type: 'receiver',
  },
  {
    id: 5,
    message:
      'I have a few meetings scheduled, but otherwise just working from home. How about you?',
    time: '12:04',
    type: 'sender',
  },
  {
    id: 1,
    message: 'Hi Theresa, good morning 😄',
    time: '12:00',
    type: 'sender',
  },
  {
    id: 2,
    message: 'Hi there, good morning! How are you?',
    time: '12:01',
    type: 'receiver',
  },
  {
    id: 3,
    message: 'I am doing well, thanks for asking 😊',
    time: '12:02',
    type: 'sender',
  },
  {
    id: 4,
    message: "That's great to hear! What are your plans for the day?",
    time: '12:03',
    type: 'receiver',
  },
  {
    id: 5,
    message:
      'I have a few meetings scheduled, but otherwise just working from home. How about you?',
    time: '12:04',
    type: 'sender',
  },
  {
    id: 1,
    message: 'Hi Theresa, good morning 😄',
    time: '12:00',
    type: 'sender',
  },
  {
    id: 2,
    message: 'Hi there, good morning! How are you?',
    time: '12:01',
    type: 'receiver',
  },
  {
    id: 3,
    message: 'I am doing well, thanks for asking 😊',
    time: '12:02',
    type: 'sender',
  },
  {
    id: 4,
    message: "That's great to hear! What are your plans for the day?",
    time: '12:03',
    type: 'receiver',
  },
  {
    id: 5,
    message:
      'I have a few meetings scheduled, but otherwise just working from home. How about you?',
    time: '12:04',
    type: 'sender',
  },
];

const AddressData = [
  {
    id: 1,
    title: 'Home',
    address: '123, Main Street, New York, USA',
    isDefault: true,
  },
  {
    id: 2,
    title: 'Office',
    address: '345, Second Street, New York, USA',
    isDefault: false,
  },
  {
    id: 3,
    title: 'Appartment',
    address: '567, Third Street, New York, USA',
    isDefault: false,
  },
  {
    id: 4,
    title: "Parent's House",
    address: '789, Fourth Street, New York, USA',
    isDefault: false,
  },
  {
    id: 5,
    title: 'Farm House',
    address: '101, Fifth Street, New York, USA',
    isDefault: false,
  },
  {
    id: 6,
    title: 'Town Square',
    address: '123, Main Street, New York, USA',
    isDefault: false,
  },
];

const walletData = [
  {
    product: 'Contemporary Sofa',
    price: '$1,500.00',
    productImage: images.sofa3,
    id: 1,
    date: 'Dec 15, 2024 | 12:00 PM',
    status: strings.orders,
  },
  {
    id: 2,
    product: strings.topUpWallet,
    price: '$200.00',
    date: 'Jan 05, 2023 | 12:50 PM',
    status: strings.topUp,
  },
  {
    product: 'Elegant Glass-Top Table',
    price: '$249.99',
    date: 'April 15, 2022 | 3:30 PM',
    status: 'in stock',
    productImage: images.table2,
    id: 3,
    status: strings.orders,
  },
  {
    product: 'Classic Oak Cupboard',
    price: '$249.99',
    date: 'July 20, 2023 | 9:30 AM',
    productImage: images.cupboard2,
    id: 4,
    date: 'Dec 13, 2024 | 03:23 AM',
    status: strings.orders,
  },
  {
    id: 5,
    product: strings.topUpWallet,
    price: '$40',
    date: 'Dec 12, 2024 | 02:50 AM',
    status: strings.topUp,
  },
  {
    id: 6,
    product: 'Chair',
    price: '$89.95',
    date: 'Dec 03, 2024 | 02:34 PM',
    status: strings.orders,
    productImage: images.chair17,
  },
  {
    id: 7,
    product: 'vase Flower',
    price: '$115.00',
    date: 'Aug 07, 2023 | 05:40 PM ',
    status: strings.orders,
    productImage: images.vase3,
  },
  {
    id: 8,
    product: 'knife Kitchen',
    price: '$19.99',
    date: 'Jul 15, 2023 | 12:00 PM',
    status: strings.orders,
    productImage: images.kitchen5,
  },
  {
    id: 9,
    product: strings.topUpWallet,
    price: '$500.00',
    date: 'Jan 05, 2023 | 12:50 PM',
    status: strings.topUp,
  },
];

const onGoingData = [
  {
    id: 2,
    product: 'Vintage Sofa',
    price: '$800.00',
    date: 'May 5, 2023 | 2:30 PM',
    status: 'orders',
    productImage: images.sofa2,
    color: '#FFFFFF',
  },
  {
    id: 4,
    product: 'Modern Glass Wardrobe',
    price: '$399.99',
    date: 'August 10, 2023 | 12:45 PM',
    status: 'out of stock',
    productImage: images.cupboard4,
    color: '#ADD8E6',
  },
  {
    id: 1,
    product: 'Marble Flower Vase',
    price: '$115.00',
    date: 'March 1, 2022 | 1:00 PM',
    status: 'orders',
    productImage: images.vase1,
    color: '#000000',
  },
  {
    id: 4,
    product: 'Rocking Chair',
    price: '$89.95',
    date: 'September 8, 2022 | 2:15 PM',
    status: 'orders',
    productImage: images.chair14,
    color: '#228B22',
  },
];

const completedOrderData = [
  {
    id: 2,
    product: 'Classic Oak Cupboard',
    price: '$249.99',
    date: 'July 20, 2023 | 9:30 AM',
    status: 'in stock',
    productImage: images.cupboard2,
    color: '#8B4513',
  },
  {
    id: 4,
    product: 'Industrial Pendant Light',
    price: '$95.00',
    date: 'July 20, 2022 | 2:15 PM',
    status: 'orders',
    productImage: images.lamp4,
  },
  {
    id: 3,
    product: 'Silicone Baking Mat',
    price: '$19.99',
    date: 'May 15, 2022 | 10:45 AM',
    status: 'orders',
    productImage: images.kitchen3,
    color: '#FFD700',
  },
  {
    id: 5,
    product: 'Space-Saving Folding Table',
    price: '$99.95',
    date: 'September 22, 2022 | 9:00 AM',
    status: 'orders',
    productImage: images.table5,
    color: '#B2B2B2',
  },
  {
    id: 5,
    product: 'Sectional Sofa',
    price: '$1,800.00',
    date: 'May 12, 2023 | 11:00 AM',
    status: 'orders',
    productImage: images.sofa5,
    color: '#C7C7C7',
  },
];

const orderStatus = [
  {
    id: 1,
    title: 'Order In Transit - Dec 17',
    time: '12:00 PM',
    status: '32 Manchester Ave. Ringgold, GA 30736',
  },
  {
    id: 2,
    title: 'Order ... Customs Port - Dec 16',
    time: '14:40 PM',
    status: '4 Evergreen Street Lake Zurich, IL 60047',
  },
  {
    id: 3,
    title: 'Orders are ... Shipped - Dec 15',
    time: '11:30 AM',
    status: '9177 Hillcrest Street Wheeling, WV 26003',
  },
  {
    id: 4,
    title: 'Order is in Packing - Dec 15',
    time: '10:25 PM',
    status: '891 Glen Ridge St. Gainesville, VA 20155',
  },
  {
    id: 5,
    title: 'Verified Payments - Dec 15',
    time: '10:04 PM',
    status: '55 Summerhouse Dr. Apopka, FL 32703',
  },
];

const orderStatusCategory = [
  {
    id: 1,
    image: images.seller,
    position: 1,
    isHide: false,
  },
  {
    id: 2,
    image: images.shipping,
    position: 2,
    isHide: true,
  },
  {
    id: 3,
    image: images.courier,
    position: 3,
    isHide: true,
  },
  {
    id: 4,
    image: images.delivered,
    position: 4,
    isHide: true,
  },
];

const homeCategoryData = [
  {
    id: 1,
    image: images.categorySofa,
    title: strings.sofa,
    data: [
      {
        id: 1,
        product: 'Mid Century Sofa',
        price: '$1,200.00',
        date: 'May 1, 2023 | 9:00 AM',
        status: 'orders',
        productImage: images.sofa1,
        color: '#000000',
        rating: '4.2',
        sold: '2.3k',
        review: '4,567',
      },
      {
        id: 2,
        product: 'Vintage Sofa',
        price: '$800.00',
        date: 'May 5, 2023 | 2:30 PM',
        status: 'orders',
        productImage: images.sofa2,
        color: '#FFFFFF',
        rating: '4.6',
        sold: '1.6k',
        review: '3,567',
      },
      {
        id: 3,
        product: 'Contemporary Sofa',
        price: '$1,500.00',
        date: 'May 8, 2023 | 10:15 AM',
        status: 'orders',
        productImage: images.sofa3,
        color: '#001C3F',
        rating: '4.9',
        sold: '1.2k',
        review: '2,567',
      },
      {
        id: 4,
        product: 'Lounge Sofa',
        price: '$1,000.00',
        date: 'May 10, 2023 | 3:45 PM',
        status: 'orders',
        productImage: images.sofa4,
        color: '#C0C0C0',
        rating: '4.4',
        sold: '1.3k',
        review: '1,567',
      },
      {
        id: 5,
        product: 'Sectional Sofa',
        price: '$1,800.00',
        date: 'May 12, 2023 | 11:00 AM',
        status: 'orders',
        productImage: images.sofa5,
        color: '#C7C7C7',
        rating: '4.7',
        sold: '1.8k',
        review: '5,567',
      },
    ],
  },
  {
    id: 2,
    image: images.categoryChair,
    title: strings.chair,
    data: [
      {
        id: 1,
        product: 'Occasional Chair',
        price: '$115.00',
        date: 'March 1, 2022 | 1:00 PM',
        status: 'orders',
        productImage: images.chair1,
        color: '#000000',
        rating: '4.4',
        sold: '4.7k',
        review: '3,567',
      },
      {
        id: 2,
        product: 'Accent Chair',
        price: '$99.99',
        date: 'July 20, 2023 | 10:30 AM',
        status: 'in stock',
        productImage: images.chair2,
        color: '#FF5733',
        rating: '4.8',
        sold: '2.1k',
        review: '2,345',
      },
      {
        id: 3,
        product: 'Eames Lounge Chair',
        price: '$799.00',
        date: 'September 5, 2023 | 3:15 PM',
        status: 'out of stock',
        productImage: images.chair3,
        color: '#2E8B57',
        rating: '4.9',
        sold: '8.3k',
        review: '9,874',
      },
      {
        id: 4,
        product: 'Rocking Chair',
        price: '$149.50',
        date: 'June 12, 2023 | 12:45 PM',
        status: 'orders',
        productImage: images.chair4,
        color: '#6A5ACD',
        rating: '4.7',
        sold: '3.2k',
        review: '4,567',
      },
      {
        id: 5,
        product: 'Wingback Chair',
        price: '$199.00',
        date: 'October 3, 2023 | 2:00 PM',
        status: 'in stock',
        productImage: images.chair5,
        color: '#FFD700',
        rating: '4.5',
        sold: '5.9k',
        review: '6,789',
      },
      {
        id: 6,
        product: 'Barcelona Chair',
        price: '$899.99',
        date: 'November 21, 2023 | 11:20 AM',
        status: 'in stock',
        productImage: images.chair6,
        color: '#B22222',
        rating: '4.6',
        sold: '7.1k',
        review: '5,432',
      },
      {
        id: 7,
        product: 'Chaise Lounge Chair',
        price: '$249.95',
        date: 'August 8, 2023 | 4:00 PM',
        status: 'orders',
        productImage: images.chair7,
        color: '#800000',
        rating: '4.3',
        sold: '2.5k',
        review: '1,234',
      },
      {
        id: 8,
        product: 'Gaming Chair',
        price: '$299.00',
        date: 'December 10, 2023 | 6:30 PM',
        status: 'in stock',
        productImage: images.chair8,
        color: '#008080',
        rating: '4.2',
        sold: '4.2k',
        review: '3,210',
      },
      {
        id: 9,
        product: 'Bean Bag Chair',
        price: '$79.95',
        date: 'April 5, 2023 | 9:45 AM',
        status: 'out of stock',
        productImage: images.chair9,
        color: '#A52A2A',
        rating: '4.0',
        sold: '1.8k',
        review: '876',
      },
      {
        id: 10,
        product: 'Papasan Chair',
        price: '$129.00',
        date: 'May 15, 2023 | 8:00 AM',
        status: 'orders',
        productImage: images.chair10,
        color: '#008000',
        rating: '4.6',
        sold: '3.8k',
        review: '2,345',
      },
    ],
  },
  {
    id: 3,
    image: images.categoryTable,
    title: strings.table,
    data: [
      {
        id: 1,
        product: 'Mini Wooden Table',
        price: '$115.00',
        date: 'March 1, 2022 | 1:00 PM',
        status: 'orders',
        productImage: images.table1,
        color: '#000000',
        rating: '4.4',
        sold: '4.7k',
        review: '3,567',
      },
      {
        id: 2,
        product: 'Elegant Glass-Top Table',
        price: '$249.99',
        date: 'April 15, 2022 | 3:30 PM',
        status: 'in stock',
        productImage: images.table2,
        color: '#F2F2F2',
        rating: '4.8',
        sold: '2.1k',
        review: '2,234',
      },
      {
        id: 3,
        product: 'Modern Marble Dining Table',
        price: '$689.00',
        date: 'July 10, 2022 | 10:15 AM',
        status: 'orders',
        productImage: images.table3,
        color: '#D6D0C4',
        rating: '4.9',
        sold: '1.8k',
        review: '1,890',
      },
      {
        id: 4,
        product: 'Rustic Farmhouse Table',
        price: '$379.50',
        date: 'June 5, 2022 | 12:45 PM',
        status: 'in stock',
        productImage: images.table4,
        color: '#7D615A',
        rating: '4.6',
        sold: '3.5k',
        review: '2,874',
      },
      {
        id: 5,
        product: 'Space-Saving Folding Table',
        price: '$99.95',
        date: 'September 22, 2022 | 9:00 AM',
        status: 'orders',
        productImage: images.table5,
        color: '#B2B2B2',
        rating: '4.2',
        sold: '5.2k',
        review: '4,012',
      },
      {
        id: 6,
        product: 'Industrial Steel Side Table',
        price: '$159.00',
        date: 'August 12, 2022 | 5:30 PM',
        status: 'in stock',
        productImage: images.table6,
        color: '#4C4C4C',
        rating: '4.7',
        sold: '2.6k',
        review: '2,345',
      },
      {
        id: 7,
        product: 'Vintage Oak Coffee Table',
        price: '$289.99',
        date: 'November 5, 2022 | 11:20 AM',
        status: 'orders',
        productImage: images.table7,
        color: '#A18665',
        rating: '4.5',
        sold: '3.1k',
        review: '2,189',
      },
      {
        id: 8,
        product: 'Adjustable Height Study Table',
        price: '$179.95',
        date: 'February 18, 2022 | 2:45 PM',
        status: 'in stock',
        productImage: images.table8,
        color: '#F0E5DB',
        rating: '4.3',
        sold: '4.9k',
        review: '3,890',
      },
    ],
  },
  {
    id: 4,
    image: images.categoryKitchen,
    title: strings.kitchen,
    data: [
      {
        id: 1,
        product: 'Mini Pottery Teapot',
        price: '$115.00',
        date: 'March 1, 2022 | 1:00 PM',
        status: 'orders',
        productImage: images.kitchen1,
        color: '#000000',
        rating: '4.4',
        sold: '4.7k',
        review: '3,567',
      },
      {
        id: 2,
        product: 'Stainless Steel Whisk',
        price: '$8.99',
        date: 'April 5, 2022 | 3:30 PM',
        status: 'orders',
        productImage: images.kitchen2,
        color: '#E5E4E2',
        rating: '4.8',
        sold: '2.1k',
        review: '1,234',
      },
      {
        id: 3,
        product: 'Silicone Baking Mat',
        price: '$19.99',
        date: 'May 15, 2022 | 10:45 AM',
        status: 'orders',
        productImage: images.kitchen3,
        color: '#FFD700',
        rating: '4.9',
        sold: '6.3k',
        review: '5,678',
      },
      {
        id: 4,
        product: 'Bamboo Cutting Board',
        price: '$29.95',
        date: 'June 10, 2022 | 12:15 PM',
        status: 'orders',
        productImage: images.kitchen4,
        color: '#008000',
        rating: '4.7',
        sold: '3.9k',
        review: '2,345',
      },
      {
        id: 5,
        product: 'Ceramic Knife Set',
        price: '$49.99',
        date: 'July 20, 2022 | 2:00 PM',
        status: 'orders',
        productImage: images.kitchen5,
        color: '#F08080',
        rating: '4.6',
        sold: '5.2k',
        review: '4,321',
      },
      {
        id: 6,
        product: 'Stainless Steel Mixing Bowls',
        price: '$39.95',
        date: 'August 5, 2022 | 11:30 AM',
        status: 'orders',
        productImage: images.kitchen6,
        color: '#C0C0C0',
        rating: '4.8',
        sold: '2.8k',
        review: '1,987',
      },
      {
        id: 7,
        product: 'Non-Stick Frying Pan',
        price: '$24.99',
        date: 'September 15, 2022 | 9:45 AM',
        status: 'orders',
        productImage: images.kitchen7,
        color: '#FF6347',
        rating: '4.5',
        sold: '4.1k',
        review: '3,456',
      },
      {
        id: 8,
        product: 'Wooden Spoon Set',
        price: '$12.95',
        date: 'October 8, 2022 | 4:20 PM',
        status: 'orders',
        productImage: images.kitchen8,
        color: '#8B4513',
        rating: '4.7',
        sold: '1.5k',
        review: '876',
      },
      {
        id: 9,
        product: 'Glass Storage Containers',
        price: '$22.50',
        date: 'November 25, 2022 | 6:00 PM',
        status: 'orders',
        productImage: images.kitchen9,
        color: '#ADD8E6',
        rating: '4.9',
        sold: '3.4k',
        review: '2,345',
      },
    ],
  },
  {
    id: 5,
    image: images.categoryLamp,
    title: strings.lamp,
    data: [
      {
        id: 1,
        product: 'Parabolic Reflector',
        price: '$115.00',
        date: 'March 1, 2022 | 1:00 PM',
        status: 'orders',
        productImage: images.lamp1,
        color: '#000000',
        rating: '4.4',
        sold: '4.7k',
        review: '3,567',
      },
      {
        id: 2,
        product: 'Vintage Desk Lamp',
        price: '$85.00',
        date: 'April 10, 2022 | 3:30 PM',
        status: 'orders',
        productImage: images.lamp2,
        color: '#874321',
        rating: '4.8',
        sold: '2.1k',
        review: '1,234',
      },
      {
        id: 3,
        product: 'Modern Floor Lamp',
        price: '$150.00',
        date: 'June 5, 2022 | 11:45 AM',
        status: 'pre-orders',
        productImage: images.lamp3,
        color: '#567890',
        rating: '4.6',
        sold: '3.2k',
        review: '2,345',
      },
      {
        id: 4,
        product: 'Industrial Pendant Light',
        price: '$95.00',
        date: 'July 20, 2022 | 2:15 PM',
        status: 'orders',
        productImage: images.lamp4,
        color: '#333333',
        rating: '4.5',
        sold: '1.9k',
        review: '1,987',
      },
      {
        id: 5,
        product: 'Crystal Chandelier',
        price: '$280.00',
        date: 'August 5, 2022 | 7:30 PM',
        status: 'pre-orders',
        productImage: images.lamp5,
        color: '#AA1122',
        rating: '4.9',
        sold: '5.3k',
        review: '4,567',
      },
      {
        id: 6,
        product: 'Tiffany Table Lamp',
        price: '$120.00',
        date: 'September 15, 2022 | 10:00 AM',
        status: 'orders',
        productImage: images.lamp6,
        color: '#66CCFF',
        rating: '4.7',
        sold: '2.8k',
        review: '2,876',
      },
      {
        id: 7,
        product: 'Rustic Wall Sconce',
        price: '$75.00',
        date: 'October 8, 2022 | 4:45 PM',
        status: 'pre-orders',
        productImage: images.lamp7,
        color: '#998877',
        rating: '4.4',
        sold: '1.5k',
        review: '1,234',
      },
      {
        id: 8,
        product: 'Minimalist Ceiling Lamp',
        price: '$110.00',
        date: 'November 25, 2022 | 12:30 PM',
        status: 'orders',
        productImage: images.lamp8,
        color: '#332211',
        rating: '4.6',
        sold: '3.1k',
        review: '2,345',
      },
      {
        id: 9,
        product: 'Art Deco Hanging Light',
        price: '$160.00',
        date: 'December 10, 2022 | 6:00 PM',
        status: 'orders',
        productImage: images.lamp9,
        color: '#CC99FF',
        rating: '4.8',
        sold: '4.2k',
        review: '3,456',
      },
      {
        id: 10,
        product: 'Mediterranean Lantern',
        price: '$90.00',
        date: 'January 5, 2023 | 9:15 AM',
        status: 'pre-orders',
        productImage: images.lamp10,
        color: '#4499AA',
        rating: '4.5',
        sold: '2.3k',
        review: '1,876',
      },
    ],
  },
  {
    id: 6,
    image: images.categoryCupboard,
    title: strings.cupboard,
    data: [
      {
        id: 1,
        product: 'Wooden Wardrobe',
        price: '$115.00',
        date: 'March 1, 2022 | 1:00 PM',
        status: 'orders',
        productImage: images.cupboard1,
        color: '#000000',
        rating: '4.4',
        sold: '4.7k',
        review: '3,567',
      },
      {
        id: 2,
        product: 'Classic Oak Cupboard',
        price: '$249.99',
        date: 'July 20, 2023 | 9:30 AM',
        status: 'in stock',
        productImage: images.cupboard2,
        color: '#8B4513',
        rating: '4.8',
        sold: '1.2k',
        review: '876',
      },
      {
        id: 3,
        product: 'Vintage Pine Armoire',
        price: '$189.00',
        date: 'May 5, 2023 | 3:15 PM',
        status: 'orders',
        productImage: images.cupboard3,
        color: '#6B8E23',
        rating: '4.2',
        sold: '2.3k',
        review: '1,234',
      },
      {
        id: 4,
        product: 'Modern Glass Wardrobe',
        price: '$399.99',
        date: 'August 10, 2023 | 12:45 PM',
        status: 'out of stock',
        productImage: images.cupboard4,
        color: '#ADD8E6',
        rating: '4.9',
        sold: '8.9k',
        review: '5,678',
      },
    ],
  },
  {
    id: 7,
    image: images.categoryVase,
    title: strings.vase,
    data: [
      {
        id: 1,
        product: 'Marble Flower Vase',
        price: '$115.00',
        date: 'March 1, 2022 | 1:00 PM',
        status: 'orders',
        productImage: images.vase1,
        color: '#000000',
        rating: '4.4',
        sold: '4.7k',
        review: '3,567',
      },
      {
        id: 2,
        product: 'Ceramic Artistic Vase',
        price: '$85.00',
        date: 'June 12, 2022 | 3:30 PM',
        status: 'orders',
        productImage: images.vase2,
        color: '#FFFFFF',
        rating: '4.8',
        sold: '2.1k',
        review: '1,245',
      },
      {
        id: 3,
        product: 'Glass Decorative Vase',
        price: '$55.00',
        date: 'September 5, 2022 | 10:15 AM',
        status: 'orders',
        productImage: images.vase3,
        color: '#00FF00',
        rating: '4.2',
        sold: '3.3k',
        review: '2,876',
      },
      {
        id: 4,
        product: 'Metallic Modern Vase',
        price: '$135.00',
        date: 'January 20, 2023 | 12:45 PM',
        status: 'orders',
        productImage: images.vase4,
        color: '#FF0000',
        rating: '4.9',
        sold: '5.4k',
        review: '4,891',
      },
    ],
  },
  {
    id: 8,
    image: images.categoryMore,
    title: strings.more,
    data: [
      {
        id: 1,
        product: 'Wingback Chair',
        price: '$115.00',
        date: 'March 1, 2022 | 1:00 PM',
        status: 'orders',
        productImage: images.chair11,
        color: '#000000',
        rating: '4.5',
        sold: '3.7k',
        review: '2,954',
      },
      {
        id: 2,
        product: 'Eames Lounge Chair',
        price: '$599.00',
        date: 'June 5, 2022 | 10:30 AM',
        status: 'orders',
        productImage: images.chair12,
        color: '#FF5733',
        rating: '4.8',
        sold: '1.2k',
        review: '1,348',
      },
      {
        id: 3,
        product: 'Bean Bag Chair',
        price: '$49.99',
        date: 'July 12, 2022 | 3:45 PM',
        status: 'orders',
        productImage: images.chair13,
        color: '#1E90FF',
        rating: '4.2',
        sold: '5.2k',
        review: '4,512',
      },
      {
        id: 4,
        product: 'Rocking Chair',
        price: '$89.95',
        date: 'September 8, 2022 | 2:15 PM',
        status: 'orders',
        productImage: images.chair14,
        color: '#228B22',
        rating: '4.6',
        sold: '2.9k',
        review: '2,186',
      },
      {
        id: 5,
        product: 'Folding Chair',
        price: '$29.99',
        date: 'December 20, 2022 | 12:00 PM',
        status: 'orders',
        productImage: images.chair15,
        color: '#FFD700',
        rating: '4.0',
        sold: '6.8k',
        review: '3,965',
      },
      {
        id: 6,
        product: 'Accent Chair',
        price: '$179.00',
        date: 'January 5, 2023 | 9:45 AM',
        status: 'orders',
        productImage: images.chair16,
        color: '#8B008B',
        rating: '4.9',
        sold: '2.3k',
        review: '1,987',
      },
      {
        id: 7,
        product: 'Barcelona Chair',
        price: '$899.00',
        date: 'February 14, 2023 | 5:30 PM',
        status: 'orders',
        productImage: images.chair17,
        color: '#FF1493',
        rating: '4.7',
        sold: '1.5k',
        review: '1,546',
      },
      {
        id: 8,
        product: 'Swivel Chair',
        price: '$129.99',
        date: 'April 10, 2023 | 11:00 AM',
        status: 'orders',
        productImage: images.chair18,
        color: '#008080',
        rating: '4.3',
        sold: '4.1k',
        review: '3,720',
      },
      {
        id: 9,
        product: 'Hammock Chair',
        price: '$67.95',
        date: 'May 25, 2023 | 2:30 PM',
        status: 'orders',
        productImage: images.chair19,
        color: '#FF6347',
        rating: '4.4',
        sold: '2.7k',
        review: '2,319',
      },
      {
        id: 10,
        product: 'Gaming Chair',
        price: '$249.00',
        date: 'July 5, 2023 | 4:20 PM',
        status: 'orders',
        productImage: images.chair20,
        color: '#32CD32',
        rating: '4.5',
        sold: '3.0k',
        review: '2,645',
      },
      {
        id: 1,
        product: 'Wooden Chair',
        price: '$198.00',
        date: 'March 1, 2022 | 1:00 PM',
        status: 'orders',
        productImage: images.chair21,
        color: '#000000',
        rating: '3.5',
        sold: '4.7k',
        review: '3,684',
      },
      {
        id: 2,
        product: 'Ergonomic Office Chair',
        price: '$249.99',
        date: 'July 20, 2023 | 10:30 AM',
        status: 'in stock',
        productImage: images.chair22,
        color: '#AABBCC',
        rating: '4.8',
        sold: '2.1k',
        review: '1,219',
      },
      {
        id: 3,
        product: 'Vintage Leather Armchair',
        price: '$349.00',
        date: 'June 5, 2023 | 3:45 PM',
        status: 'orders',
        productImage: images.chair23,
        color: '#774455',
        rating: '4.6',
        sold: '1.8k',
        review: '985',
      },
      {
        id: 4,
        product: 'Modern Plastic Chair',
        price: '$89.99',
        date: 'April 10, 2023 | 12:15 PM',
        status: 'in stock',
        productImage: images.chair24,
        color: '#00FF00',
        rating: '4.2',
        sold: '3.2k',
        review: '2,315',
      },
      {
        id: 5,
        product: 'Rocking Chair',
        price: '$159.00',
        date: 'August 2, 2023 | 4:20 PM',
        status: 'in stock',
        productImage: images.chair25,
        color: '#663399',
        rating: '4.9',
        sold: '1.5k',
        review: '1,534',
      },
      {
        id: 6,
        product: 'Outdoor Folding Chair',
        price: '$49.99',
        date: 'May 15, 2023 | 9:00 AM',
        status: 'orders',
        productImage: images.chair26,
        color: '#FFA500',
        rating: '4.0',
        sold: '2.9k',
        review: '1,831',
      },
      {
        id: 7,
        product: 'Swivel Gaming Chair',
        price: '$279.00',
        date: 'July 1, 2023 | 2:30 PM',
        status: 'in stock',
        productImage: images.chair27,
        color: '#FF0000',
        rating: '4.7',
        sold: '2.3k',
        review: '1,908',
      },
    ],
  },
];

const mostPopularData = [
  strings.all,
  strings.sofa,
  strings.kitchen,
  strings.table,
  strings.chair,
  strings.lamp,
  strings.cupboard,
  strings.vase,
  strings.more,
];

const homeProductData = [
  {
    id: 9,
    product: 'Hammock Chair',
    price: '$69.95',
    date: 'May 25, 2023 | 2:30 PM',
    status: 'orders',
    productImage: images.chair19,
    color: '#FF6347',
    rating: '4.4',
    sold: '2.7k',
    review: '2,319',
  },
  {
    id: 2,
    product: 'Ceramic Artistic Vase',
    price: '$85.00',
    date: 'June 12, 2022 | 3:30 PM',
    status: 'orders',
    productImage: images.vase2,
    color: '#FFFFFF',
    rating: '4.8',
    sold: '2.1k',
    review: '1,245',
  },
  {
    id: 6,
    product: 'Tiffany Table Lamp',
    price: '$120.00',
    date: 'September 15, 2022 | 10:00 AM',
    status: 'orders',
    productImage: images.lamp6,
    color: '#66CCFF',
    rating: '4.7',
    sold: '2.8k',
    review: '2,876',
  },
  {
    id: 8,
    product: 'Adjustable Height Study Table',
    price: '$179.95',
    date: 'February 18, 2022 | 2:45 PM',
    status: 'in stock',
    productImage: images.table8,
    color: '#F0E5DB',
    rating: '4.3',
    sold: '4.9k',
    review: '3,890',
  },
  {
    id: 9,
    product: 'Glass Storage Containers',
    price: '$22.50',
    date: 'November 25, 2022 | 6:00 PM',
    status: 'orders',
    productImage: images.kitchen9,
    color: '#ADD8E6',
    rating: '4.9',
    sold: '3.4k',
    review: '2,345',
  },
  {
    id: 5,
    product: 'Sectional Sofa',
    price: '$1,800.00',
    date: 'May 12, 2023 | 11:00 AM',
    status: 'orders',
    productImage: images.sofa5,
    color: '#C7C7C7',
    rating: '4.7',
    sold: '1.8k',
    review: '5,567',
  },
];

const notificationData = [
  {
    title: 'Today',
    data: [
      {
        id: 1,
        image: images.discountIcon,
        title: '30% Special Discount!',
        description: 'Special promotion only valid today',
      },
    ],
  },
  {
    title: 'Yesterday',
    data: [
      {
        id: 1,
        image: images.walletIcon,
        title: 'Top Up E-Wallet Successful!',
        description: 'You have to top up your e-wallet',
      },
      {
        id: 1,
        image: images.locationIcon,
        title: 'New Services Available!',
        description: 'Now you can track orders in real time',
      },
    ],
  },
  {
    title: 'December 22, 2024',
    data: [
      {
        id: 1,
        image: images.creditCardIcon,
        title: 'Credit Card Connected!',
        description: 'Credit Card has been linked!',
      },
      {
        id: 1,
        image: images.profileIcon,
        title: 'Account Setup Successful!',
        description: 'Your account has been created!',
      },
    ],
  },
];

const colorData = [
  '#7A5548',
  '#797979',
  '#9F9F9F',
  '#673AB3',
  '#FF981F',
  '#607D8A',
  '#3F51B2',
];

const ratingData = [strings.all, '5', '4', '3', '2', '1'];

const reviewsData = [
  {
    id: 1,
    name: 'John Duew',
    image: 'https://randomuser.me/api/portraits/men/1.jpg',

    rating: 5,
    review:
      'The item is very good, my son likes it very much and plays every day 💯💯💯',
    like: 352,
    time: '6 days ago',
  },
  {
    id: 2,
    name: 'Jane Doe',
    image: 'https://randomuser.me/api/portraits/women/1.jpg',

    rating: 4,
    review:
      'The item is good, but it could be better. My son likes it, but he has some complaints about it.',
    like: 100,
    time: '2 days ago',
  },
  {
    id: 3,
    name: 'Bob Smith',
    image: 'https://randomuser.me/api/portraits/men/2.jpg',

    rating: 3,
    review:
      'The item is okay, but it could be better. My son likes it, but he has some complaints about it.',
    like: 50,
    time: '1 day ago',
  },
  {
    id: 4,
    name: 'Alice Johnson',
    image: 'https://randomuser.me/api/portraits/women/2.jpg',

    rating: 2,
    review:
      'The item is not very good. My son does not like it very much and does not play with it often.',
    like: 10,
    time: '1 hour ago',
  },
  {
    id: 5,
    name: 'Tom Hanks',
    image: 'https://randomuser.me/api/portraits/men/3.jpg',

    rating: 1,
    review:
      'The item is terrible. My son hates it and does not play with it at all.',
    like: 1,
    time: '1 minute ago',
  },
  {
    id: 6,
    name: 'Megan Fox',
    image: 'https://randomuser.me/api/portraits/women/3.jpg',

    rating: 5,
    review:
      'The item is very good, my son likes it very much and plays every day 💯💯💯',
    like: 352,
    time: '6 days ago',
  },
  {
    id: 7,
    name: 'Samantha Smith',
    image: 'https://randomuser.me/api/portraits/women/4.jpg',

    rating: 4,
    review:
      'The item is good, but it could be better. My daughter likes it, but she has some complaints about it.',
    like: 200,
    time: '3 days ago',
  },
  {
    id: 8,
    name: 'David Johnson',
    image: 'https://randomuser.me/api/portraits/men/4.jpg',

    rating: 3,
    review:
      'The item is okay, but it could be better. My daughter likes it, but she has some complaints about it.',
    like: 100,
    time: '2 days ago',
  },
  {
    id: 9,
    name: 'Emily Brown',
    image: 'https://randomuser.me/api/portraits/women/5.jpg',

    rating: 2,
    review:
      'The item is not very good. My daughter does not like it very much and does not play with it often.',
    like: 20,
    time: '1 day ago',
  },
  {
    id: 10,
    name: 'Olivia Davis',
    image: 'https://randomuser.me/api/portraits/women/6.jpg',

    rating: 1,
    review:
      'The item is terrible. My daughter hates it and does not play with it at all.',
    like: 2,
    time: '1 hour ago',
  },
  {
    id: 11,
    name: 'Sophia Wilson',
    image: 'https://randomuser.me/api/portraits/women/7.jpg',

    rating: 5,
    review:
      'The item is very good, my daughter likes it very much and plays every day 💯💯💯',
    like: 352,
    time: '6 days ago',
  },
];

const sortAndFilterData = [
  strings.mostPopular,
  strings.mostRecent,
  strings.oldest,
  strings.priceLowToHigh,
  strings.priceHighToLow,
];

const shippingData = [
  {
    id: 1,
    title: 'Truck',
    description: 'Delivery in 3-5 days',
    price: '$200',
    image: images.shipping,
  },
  {
    id: 2,
    title: 'Train',
    description: 'Delivery in 2-3 days',
    price: '$250',
    image: images.train,
  },
  {
    id: 3,
    title: 'Container Ship',
    description: 'Delivery in 1-2 days',
    price: '$300',
    image: images.ship,
  },
  {
    id: 3,
    title: 'Plane',
    description: 'Delivery in 1 days',
    price: '$350',
    image: images.plane,
  },
];

const addPromoData = [
  {
    id: 1,
    title: 'Special 25% Off',
    description: 'Special promo only today!',
  },
  {
    id: 2,
    title: 'Discount 30% Off',
    description: 'New user special promo',
  },
  {
    id: 3,
    title: 'Special 20% Off',
    description: 'Special promo only today!',
  },
  {
    id: 4,
    title: 'Discount 15% Off',
    description: 'Special promo only valid today!',
  },
  {
    id: 5,
    title: 'Discount 35% Off',
    description: 'Special promo only valid today!',
  },
];

export {
  ProfileSetting,
  GenderData,
  OnBoardingSlide,
  contactUsData,
  helperCategoryData,
  helperData,
  languageData,
  privacyPolicyData,
  userDetail,
  chatData,
  AddressData,
  walletData,
  onGoingData,
  orderStatus,
  orderStatusCategory,
  completedOrderData,
  homeCategoryData,
  mostPopularData,
  homeProductData,
  notificationData,
  colorData,
  ratingData,
  reviewsData,
  sortAndFilterData,
  shippingData,
  addPromoData,
};
